#!/bin/busybox ash

mkdir /dev /proc /sys /sbin
mount -t devtmpfs none /dev
mount -t proc none /proc

mknod /dev/console c 5 1
mknod /dev/ttyS0 c 5 1
mknod /dev/null c 1 3
mknod /dev/htifbd0 b 254 0

mkdir /usr /usr/bin
/bin/busybox --install

mkdir /root

cat /share/riscv-logo > /dev/console

ls /dev > /dev/console
mkdir /mnt
mount -t ext4 /dev/htifbd0 /mnt >& /dev/console
ls /mnt >& /dev/console
mount >& /dev/console
exec busybox switch_root -c /dev/console /mnt /sbin/init >& /dev/console

exec /sbin/init
